version: '3.8'

services:
  image2tracker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image2tracker
    ports:
      - "1338:8000"
    environment:
      - OPENAI_API_KEY=885a33a9-169b-498f-942a-549f7a80dd02
      - MODEL_ID=google/gemma-3-27b-it
    restart: unless-stopped