version: '3.8'

services:
  course-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule-creator
    ports:
      - "1341:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_ID=${MODEL_ID}
    restart: unless-stopped