version: '3.9'

services:
  backend:
    build: .
    container_name: urtraining-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    # environment:
    #   - DATABASE_URL=postgresql://uruser:urpassword@db:5432/urtraining
    #   - SECRET_KEY=your-super-secret-key-change-in-production-please
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    container_name: urtraining-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: uruser
      POSTGRES_PASSWORD: urpassword
      POSTGRES_DB: urtraining
    volumes:
      - backend_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uruser -d urtraining"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  backend_postgres_data:
