name: CourseAssistant Deploy

on:
  push:
    branches: [ "main" ]
    paths: [ "ml/course-assisstant/**" ]
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: [ "ml/course-assisstant/**" ]

jobs:
  deploy:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged)
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ml-course-assisstant with flock and logs
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            LOG_FILE=~/deploy-course-assistant.log
            {
              echo "[$(date)] Starting course-assistant deployment"

              flock /tmp/course-assistant-deploy.lock -c '
                cd ~/UrTraining
                echo "[$(date)] Pulling latest changes..."
                git pull origin main
                set -e
                cd ml/course-assisstant || exit 1

                echo "[$(date)] Stopping containers..."
                docker-compose down

                echo "[$(date)] Rebuilding containers..."
                docker-compose build --no-cache

                echo "[$(date)] Starting containers..."
                docker-compose up -d

                echo "[$(date)] Deployment finished successfully"
              '
            } >> $LOG_FILE 2>&1
