name: Frontend Deploy

on:
  push:
    branches: [ "main" ]
    paths: [ "frontend/**" ]
  pull_request:
    types: [closed]
    branches: [ "main" ]
    paths: [ "frontend/**" ]

jobs:
  deploy:
    if: |
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && github.event.pull_request.merged)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd UrTraining
            git pull origin main
            cd frontend
            npm install
            npm run build
            sudo rm -rf /var/www/myfrontend/*
            sudo cp -r dist/* /var/www/myfrontend/
            sudo systemctl restart nginx